"""Helper functions extracted from ValidationAgent for testability.

These are pure data-construction functions that don't need access to the
agent's database connection or message queue.
"""

from __future__ import annotations

from typing import Any

from src.database import OpportunityCluster
from src.opportunity_evaluation import build_opportunity_evaluation


def build_canonical_opportunity_evaluation(
    *,
    run_id: str,
    finding_id: int,
    finding_kind: str,
    atom_summary: dict[str, Any],
    evidence_scores: dict[str, Any],
    corroboration: dict[str, Any],
    market_enrichment: dict[str, Any],
    review_feedback: dict[str, Any],
    market_score: float,
    technical_score: float,
    distribution_score: float,
    overall_score: float,
    cluster_id: int,
    cluster: OpportunityCluster,
    market_gap: dict[str, Any],
    scorecard: dict[str, Any],
    opportunity_id: int | None,
    validation_plan: dict[str, Any],
    counterevidence: list[dict[str, Any]],
    decision: dict[str, Any],
    selection_status: str,
    selection_reason: str,
    selection_gate: dict[str, Any],
    promotion_threshold: float,
    park_threshold: float,
    validation_id: int | None = None,
) -> dict[str, Any]:
    """Build the canonical evaluation snapshot from current validation state."""
    evaluation_evidence = {
        "market_gap_state": market_gap["market_gap"],
        "market_gap": dict(market_gap or {}),
        "recurrence_state": evidence_scores["evidence"].get("recurrence_state"),
        "family_confirmation_count": evidence_scores["evidence"].get("family_confirmation_count", 0),
        "counterevidence": counterevidence,
        "validation_plan": validation_plan,
    }
    return build_opportunity_evaluation(
        run_id=run_id,
        finding_id=finding_id,
        cluster_id=cluster_id,
        opportunity_id=opportunity_id,
        validation_id=validation_id,
        source_finding_kind=finding_kind,
        atom_summary=atom_summary,
        validation_inputs={
            "problem_score": evidence_scores["problem_score"],
            "solution_gap_score": evidence_scores["solution_gap_score"],
            "saturation_score": evidence_scores["saturation_score"],
            "feasibility_score": evidence_scores["feasibility_score"],
            "value_score": evidence_scores["value_score"],
            "market_score": market_score,
            "technical_score": technical_score,
            "distribution_score": distribution_score,
            "overall_score": overall_score,
            "cluster_signal_count": int(getattr(cluster, "signal_count", 0) or 0),
            "cluster_atom_count": int(getattr(cluster, "atom_count", 0) or 0),
            "recurrence_timeout": evidence_scores["evidence"].get("recurrence_timeout", False),
            "competitor_timeout": evidence_scores["evidence"].get("competitor_timeout", False),
        },
        corroboration_inputs={
            "recurrence_state": evidence_scores["evidence"].get("recurrence_state"),
            "corroboration_score": float(corroboration.get("corroboration_score", 0.0) or 0.0),
            "evidence_sufficiency": float(corroboration.get("evidence_sufficiency", 0.0) or 0.0),
            "query_coverage": float(corroboration.get("query_coverage", 0.0) or 0.0),
            "family_confirmation_count": evidence_scores["evidence"].get("family_confirmation_count", 0),
            "source_family_diversity": int(corroboration.get("source_family_diversity", 0) or 0),
            "core_source_family_diversity": int(corroboration.get("core_source_family_diversity", 0) or 0),
            "cluster_source_family_diversity": int(corroboration.get("cluster_source_family_diversity", 0) or 0),
            "cluster_origin_family_diversity": int(corroboration.get("cluster_origin_family_diversity", 0) or 0),
            "cross_source_match_score": float(corroboration.get("cross_source_match_score", 0.0) or 0.0),
            "generalizability_class": str(corroboration.get("generalizability_class", "") or ""),
            "generalizability_score": float(corroboration.get("generalizability_score", 0.0) or 0.0),
        },
        market_enrichment_inputs={
            "demand_score": float(market_enrichment.get("demand_score", 0.0) or 0.0),
            "buyer_intent_score": float(market_enrichment.get("buyer_intent_score", 0.0) or 0.0),
            "competition_score": float(market_enrichment.get("competition_score", 0.0) or 0.0),
            "trend_score": float(market_enrichment.get("trend_score", 0.0) or 0.0),
            "review_signal_score": float(market_enrichment.get("review_signal_score", 0.0) or 0.0),
            "operational_buyer_score": float(market_enrichment.get("operational_buyer_score", 0.0) or 0.0),
            "cost_pressure_score": float(market_enrichment.get("cost_pressure_score", 0.0) or 0.0),
            "willingness_to_pay_signal": float(market_enrichment.get("willingness_to_pay_signal", 0.0) or 0.0),
            "multi_source_value_lift": float(market_enrichment.get("multi_source_value_lift", 0.0) or 0.0),
            "wedge_active": bool(market_enrichment.get("wedge_active")),
            "wedge_fit_score": float(market_enrichment.get("wedge_fit_score", 0.0) or 0.0),
        },
        review_feedback_inputs={
            "count": int(review_feedback.get("count", 0) or 0),
            "labels": review_feedback.get("labels", []),
            "strongest_label": review_feedback.get("strongest_label", ""),
            "strongest_count": int(review_feedback.get("strongest_count", 0) or 0),
            "consistency": float(review_feedback.get("consistency", 0.0) or 0.0),
            "park_bias": float(review_feedback.get("park_bias", 0.0) or 0.0),
            "kill_bias": float(review_feedback.get("kill_bias", 0.0) or 0.0),
        },
        measures=scorecard,
        evidence=evaluation_evidence,
        decision=decision["recommendation"],
        decision_reason=decision.get("decision_reason", decision.get("reason", "")),
        promotion_threshold=promotion_threshold,
        park_threshold=park_threshold,
        selection_status=selection_status,
        selection_reason=selection_reason,
        selection_checks=selection_gate,
    )


def build_evidence_payload(
    *,
    run_id: str,
    finding_id: int,
    finding_kind: str,
    title: str,
    summary: str,
    atom_summary: dict[str, Any],
    evidence_scores: dict[str, Any],
    corroboration: dict[str, Any],
    market_enrichment: dict[str, Any],
    review_feedback: dict[str, Any],
    market_score: float,
    technical_score: float,
    distribution_score: float,
    overall_score: float,
    cluster_id: int,
    cluster: OpportunityCluster,
    market_gap: dict[str, Any],
    scorecard: dict[str, Any],
    opportunity_id: int,
    experiment_id: int,
    validation_plan: dict[str, Any],
    counterevidence: list[dict[str, Any]],
    decision: dict[str, Any],
    selection_status: str,
    selection_reason: str,
    selection_gate: dict[str, Any],
    gate_threshold: float,
    promotion_threshold: float,
    park_threshold: float,
    high_leverage: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Build the full evidence payload dict for a validation result.

    This was extracted from ValidationAgent._build_evidence_payload to make
    the data construction testable in isolation.
    """
    stage_gates = {
        "signal_gate": bool(cluster.evidence_quality >= 0.35 and cluster.atom_count >= 1),
        "cluster_gate": bool(cluster.atom_count >= 1),
        "opportunity_gate": bool(scorecard["composite_score"] >= promotion_threshold),
    }
    evaluation = build_canonical_opportunity_evaluation(
        run_id=run_id,
        finding_id=finding_id,
        finding_kind=finding_kind,
        atom_summary=atom_summary,
        evidence_scores=evidence_scores,
        corroboration=corroboration,
        market_enrichment=market_enrichment,
        review_feedback=review_feedback,
        market_score=market_score,
        technical_score=technical_score,
        distribution_score=distribution_score,
        overall_score=overall_score,
        cluster_id=cluster_id,
        cluster=cluster,
        market_gap=market_gap,
        scorecard=scorecard,
        opportunity_id=opportunity_id,
        validation_plan=validation_plan,
        counterevidence=counterevidence,
        decision=decision,
        selection_status=selection_status,
        selection_reason=selection_reason,
        selection_gate=selection_gate,
        promotion_threshold=promotion_threshold,
        park_threshold=park_threshold,
    )
    return {
        "finding_id": finding_id,
        "finding_kind": finding_kind,
        "park_subreason": decision.get("park_subreason", ""),
        "recurrence_timeout": evidence_scores["evidence"].get("recurrence_timeout", False),
        "competitor_timeout": evidence_scores["evidence"].get("competitor_timeout", False),
        "recurrence_state": evidence_scores["evidence"].get("recurrence_state"),
        "recurrence_gap_reason": evidence_scores["evidence"].get("recurrence_gap_reason", ""),
        "recurrence_failure_class": evidence_scores["evidence"].get("recurrence_failure_class", ""),
        "queries_considered": evidence_scores["evidence"].get("queries_considered", []),
        "queries_executed": evidence_scores["evidence"].get("queries_executed", []),
        "recurrence_budget_profile": evidence_scores["evidence"].get("recurrence_budget_profile", {}),
        "candidate_meaningful": evidence_scores["evidence"].get("candidate_meaningful", {}),
        "recurrence_probe_summary": evidence_scores["evidence"].get("recurrence_probe_summary", {}),
        "recurrence_source_branch": evidence_scores["evidence"].get("recurrence_source_branch", {}),
        "last_action": evidence_scores["evidence"].get("last_action", ""),
        "last_transition_reason": evidence_scores["evidence"].get("last_transition_reason", ""),
        "chosen_family": evidence_scores["evidence"].get("chosen_family", ""),
        "expected_gain_class": evidence_scores["evidence"].get("expected_gain_class", ""),
        "source_attempts_snapshot": evidence_scores["evidence"].get("source_attempts_snapshot", {}),
        "skipped_families": evidence_scores["evidence"].get("skipped_families", {}),
        "controller_actions": evidence_scores["evidence"].get("controller_actions", []),
        "budget_snapshot": evidence_scores["evidence"].get("budget_snapshot", {}),
        "fallback_strategy_used": evidence_scores["evidence"].get("fallback_strategy_used", ""),
        "decomposed_atom_queries": evidence_scores["evidence"].get("decomposed_atom_queries", []),
        "routing_override_reason": evidence_scores["evidence"].get("routing_override_reason", ""),
        "cohort_query_pack_used": evidence_scores["evidence"].get("cohort_query_pack_used", False),
        "cohort_query_pack_name": evidence_scores["evidence"].get("cohort_query_pack_name", ""),
        "web_query_strategy_path": evidence_scores["evidence"].get("web_query_strategy_path", []),
        "specialized_surface_targeting_used": evidence_scores["evidence"].get("specialized_surface_targeting_used", False),
        "promotion_gap_class": evidence_scores["evidence"].get("promotion_gap_class", ""),
        "near_miss_enrichment_action": evidence_scores["evidence"].get("near_miss_enrichment_action", ""),
        "sufficiency_priority_reason": evidence_scores["evidence"].get("sufficiency_priority_reason", ""),
        "value_enrichment_used": evidence_scores["evidence"].get("value_enrichment_used", False),
        "value_enrichment_queries": evidence_scores["evidence"].get("value_enrichment_queries", []),
        "value_enrichment_docs": evidence_scores["evidence"].get("value_enrichment_docs", []),
        "matched_results_by_source": evidence_scores["evidence"].get("matched_results_by_source", {}),
        "partial_results_by_source": evidence_scores["evidence"].get("partial_results_by_source", {}),
        "matched_docs_by_source": evidence_scores["evidence"].get("matched_docs_by_source", {}),
        "partial_docs_by_source": evidence_scores["evidence"].get("partial_docs_by_source", {}),
        "family_confirmation_count": evidence_scores["evidence"].get("family_confirmation_count", 0),
        "source_yield": evidence_scores["evidence"].get("source_yield", {}),
        "reshaped_query_history": evidence_scores["evidence"].get("reshaped_query_history", []),
        "scores": {
            "problem_score": evidence_scores["problem_score"],
            "solution_gap_score": evidence_scores["solution_gap_score"],
            "saturation_score": evidence_scores["saturation_score"],
            "feasibility_score": evidence_scores["feasibility_score"],
            "value_score": evidence_scores["value_score"],
            "market_score": market_score,
            "technical_score": technical_score,
            "distribution_score": distribution_score,
            "overall_score": overall_score,
        },
        "gates": {
            "recurring_problem": evidence_scores["problem_score"] >= gate_threshold,
            "solution_gap": evidence_scores["solution_gap_score"] >= 0.4,
            "saturation": evidence_scores["saturation_score"] >= 0.35,
            "feasibility": evidence_scores["feasibility_score"] >= gate_threshold,
            "value": evidence_scores["value_score"] >= 0.45,
            **stage_gates,
        },
        "summary": {
            "problem_statement": title,
            "value_signal": summary[:300],
        },
        "cluster": {
            "cluster_id": cluster_id,
            "cluster_key": cluster.cluster_key,
            "label": cluster.label,
            "summary": cluster.summary,
            "atom_count": cluster.atom_count,
            "signal_count": cluster.signal_count,
            "evidence_quality": cluster.evidence_quality,
        },
        "opportunity_id": opportunity_id,
        "experiment_id": experiment_id,
        "opportunity_evaluation": evaluation,
        "high_leverage": high_leverage or {},
    }
